services:
  lighthouse:
    extends:
      file: docker-compose-chrome.yaml
      service: chrome
    environment:
      CHROME_DEBUG_PORT: "${CHROME_DEBUG_PORT:-9159}"
      LIGHTHOUSE_LOG_EXTRA: "${LIGHTHOUSE_LOG_EXTRA:-}"
      TRANCO_LOWER_LIMIT: "${TRANCO_LOWER_LIMIT:-0}"
      TRANCO_UPPER_LIMIT: "${TRANCO_UPPER_LIMIT:-50}"
    build:
      context: .
      dockerfile: Dockerfile.lighthouse
    image: cbor-dns-eval/lighthouse
    volumes:
      - .:/app
      - ./chrome-config/.config/google-chrome-lighthouse:/tmp/chrome-lighthouse-config
      - ./custom-wrapped-chrome:/usr/bin/wrapped-chrome
    working_dir: /app
    command: |
      sh -c "PUID='${PUID:-1000}' LIGHTHOUSE_LOG_EXTRA='${LIGHTHOUSE_LOG_EXTRA:-}' TRANCO_LOWER_LIMIT='${TRANCO_LOWER_LIMIT:-0}' TRANCO_UPPER_LIMIT='${TRANCO_UPPER_LIMIT:-50}' MARKER_DOMAIN='${MARKER_DOMAIN:-tud.de}' /app/lighthouse.sh"
