services:
  remote-proxy:
    extends:
      file: proxy.yaml
      service: proxy-base
    environment:
      PROXY_LOG: "${PROXY_REMOTE_LOG:-/app/output-dataset/mitmproxy-remote.log}"
      PROXY_PORT: "${PROXY_REMOTE_PORT:-8081}"
      PROXY_SCRIPT: "${PROXY_REMOTE_SCRIPT:-/app/remote_proxy.py}"
    networks:
      remote:
        # ipv4_address: 172.17.12.2
    volumes:
      - "./mitmproxy-remote:/root/.mitmproxy"
    ports:
      - "${PROXY_REMOTE_PORT:-8081}:${PROXY_REMOTE_PORT:-8081}"
    command: /app/remote_proxy.sh

networks:
  remote:
    # ipam:
    #   config:
    #   - subnet: "172.17.0.0/16"

