services:
  chrome:
    image: lscr.io/linuxserver/chrome:latest
    environment:
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      TZ: Europe/Berlin
      CHROME_DEBUG_PORT: "${CHROME_DEBUG_PORT:-9159}"
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./chrome-config:/config
      - ./init_chrome.sh:/init.sh
      - "./mitmproxy-local:/mitmproxy-local"
    cap_add:
      - NET_ADMIN
    shm_size: 1gb
    command:
      - /init.sh
