services:
  proxy-base:
    build:
      context: .
      dockerfile: Dockerfile.mitmproxy
    image: docker.io/miri64/tnsm26-cbor-proxy
    environment:
      PROXY_LOG: "${PROXY_LOG:-/app/mitmproxy.log}"
    volumes:
      - .:/app
      - ../04_cbor4dns_eval/cbor4dns:/cbor4dns
