name: Test notebook

on:
  push:
    branches:
      - clean   # TBD
    tags:
      - '*'
  pull_request:
    branches:
      - clean  # TBD
  schedule:
    - cron: '14 3 * * 2'

jobs:
  test:
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-latest
        notebook:
          - name: 00_start
          - name: 01_introduction
            postcondition: >
              git status --porcelain |
                grep -E "^\s+M\s+01_introduction/plots/http-archive-bytes-total.pdf"
          - name: 02_background
          - name: 03_json2cbor_eval
            postcondition: >
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json-names-percentage.pdf" &&
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json-taxonomy-content-type.pdf" &&
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json-taxonomy-redundancy.pdf" &&
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json-taxonomy-structure.pdf" &&
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json-taxonomy-tier.pdf" &&
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json2cbor-blobs-gain.pdf" &&
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json2cbor-blobs-savings.pdf" &&
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json2cbor-gain.pdf" &&
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json2cbor-savings.pdf" &&
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json2cbor-times_dumps_epyc7702.pdf" &&
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json2cbor-times_dumps_rpi3.pdf" &&
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json2cbor-times_loads_epyc7702.pdf" &&
              git status --porcelain | grep -E "^\s+M\s+03_json2cbor_eval/plots/json2cbor-times_loads_rpi3.pdf"
          - name: 03_json2cbor_eval/01_dataset_collection
            prepare: echo "${GITHUB_TOKEN}" > 03_json2cbor_eval/.gh_token
            postcondition: >
              tmux ls | grep "^scrape_github_repos:" &&
              tmux ls | grep "^json2cbor:" &&
              echo "Pane of scrape_github_repos" &&
              tmux capture-pane -t "scrape_github_repos" -pS - &&
              echo "Pane of json2cbor" &&
              tmux capture-pane -t "json2cbor" -pS -
          - name: 04_cbor4dns_eval
          - name: 04_cbor4dns_eval/01_dataset_collection
          - name: 04_cbor4dns_eval/02_encoding
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Install Ubuntu dependencies
      run: sudo ./ubuntu-setup.sh
    - name: Install Pyenv dependencies
      run: ./pyenv-setup.sh
    - name: Prepare for ${{ matrix.notebook.name }}
      if: ${{ matrix.notebook.prepare }}
      shell: bash
      continue-on-error: true # TBD
      run: ${{ matrix.notebook.prepare }}
    - name: Test ${{ matrix.notebook.name }}
      shell: bash
      continue-on-error: true # TBD
      run: |
          export PATH=~/.pyenv/bin:${PATH}
          eval "$(pyenv init -)"
          pyenv activate cbor-dns-eval-tbd
          jupyter execute --inplace ${{ matrix.notebook.name }}.ipynb
    - name: Show ${{ matrix.notebook.name }} diff
      shell: bash
      run: git diff ${{ matrix.notebook.name }}.ipynb
    - name: Check post contition for ${{ matrix.notebook.name }} 
      if: ${{ matrix.notebook.postcondition }}
      shell: bash
      run: ${{ matrix.notebook.postcondition }}
